#define CSP_LITTLE_ENDIAN 1
#define CSP_BIG_ENDIAN 0

#define CSP_POSIX 0
#define CSP_ZEPHYR 0
#define CSP_FREERTOS 1

#define CSP_DEFAULT_ROUTE 0
#define CSP_HAVE_STDIO 1
#define CSP_ENABLE_CSP_PRINT 1
#define CSP_PRINT_STDIO 0

#define CSP_QFIFO_LEN 15
#define CSP_PORT_MAX_BIND 16
#define CSP_CONN_RXQUEUE_LEN 16
#define CSP_CONN_MAX 8
#define CSP_BUFFER_SIZE 256
#define CSP_BUFFER_COUNT 15
#define CSP_RDP_MAX_WINDOW 5
#define CSP_RTABLE_SIZE 10
#define CSP_VERSION 1
#define CSP_LOG_LEVEL_DEBUG 1

#define CSP_USE_RDP 1
#define CSP_USE_CRC32 1
#define CSP_USE_HMAC 0
#define CSP_USE_PROMISC 0
#define CSP_USE_DEDUP 0
#define CSP_DEBUG 1
#define CSP_USE_EXTERNAL_DEBUG 0
#define CSP_HAVE_LIBSOCKETCAN 0
